### ISSUE TITLE
Update opt out button UI and UX

### ISSUE THREAD

**Issue by ScottDowne** [mozmar/snippets#86]
Hey @glogiotatidis I was wondering what your thoughts were on updating the opt out button to work more like: http://people.mozilla.org/%7Eshorlander/about-home-snippet-opt-out/about-home-test-02.html

Also take note that the hover state UX changes, hovering on the whole snippet, and not just the button, creates a glow effect.

This is also pretty different than the `block-snippet-overlay-glow` and might conflict.

**Comment by glogiotatidis** [comment]
What we have now was designed on request to look the way it is. It's unclear to me whether this new design is the official thing we should be targeting?

If yes I'm not against this change given that all the documentation and popular snippet templates are updated to this new design.

**Comment by ScottDowne** [comment]
I'm going to leave this open, but @glogiotatidis feel free to close, as this won't be a priority for me yet.

**Comment by glogiotatidis** [comment]
I believe we did this, closing
