### ISSUE TITLE
Report of fundraising snippet opt out not working

### ISSUE THREAD

**Issue by ScottDowne** [mozmar/snippets#97]
@glogiotatidis this is currently not working on the live fundraising snippet.

Not sure yet if it's in the snippet itself, or the snippet-service.

I'm looking into it now, but any help here is appreciated.

**Comment by ScottDowne** [comment]
It also looks like it's busted in the new signup snippet.

So, I'm leaning towards, and going to start by looking at, code in the snippet service.

**Comment by ScottDowne** [comment]
Might be the cause. Looks like index db might be throwing this error: "A mutation operation was attempted on a database that did not allow mutations."

**Comment by glogiotatidis** [comment]
It works for me just fine. For en-us we're running multiple versions of fundraising snippet right now, are you sure you're not getting the different version which looks alike?

**Comment by glogiotatidis** [comment]
You can verify that a snippet gets in the block list using  `getBlockList()` from the dev console

**Comment by ScottDowne** [comment]
I'm getting a version with the x button in it, and it's def not working for me.

Good to hear it's working for some. I'll check the `getBlockList()`

**Comment by glogiotatidis** [comment]
> I'm getting a version with the x button in it, and it's def not working for me.

All versions have an X button. All I'm saying is that we run two EOY snippets at the same time and X-ing one and immediately getting the other can make one believe that X is not working.

**Comment by ScottDowne** [comment]
Ah, I see. Looks like `getBlockList` returns an empty array, even after clicking the x.

**Comment by glogiotatidis** [comment]
Do you get this every time?

> "A mutation operation was attempted on a database that did not allow mutations."

**Comment by ScottDowne** [comment]
I only got that error in a private tab, which not sure what I expected by trying that.

Normally, I get this on load: `UnknownError` in `  aboutHome.js:130:20` which is code that looks like this:

```
  let openRequest = indexedDB.open(DATABASE_NAME, {version: DATABASE_VERSION,
                                                   storage: DATABASE_STORAGE});

  openRequest.onerror = function (event) {
    // Try to delete the old database so that we can start this process over
    // next time.
    indexedDB.deleteDatabase(DATABASE_NAME);
    invokeCallbacks();
  };
```

If I breakpoint in the onerror, it hits it, and it happens on page load, not when I click the x button.

If I click the x button, the page just reloads with the snippet still there.

**Comment by glogiotatidis** [comment]
> I only got that error in a private tab, which not sure what I expected by trying that.

Interesting I don't think we've testing against that

**Comment by glogiotatidis** [comment]
Which version are you on?

**Comment by ScottDowne** [comment]
Yeah, I wouldn't worry too much about the private tab error, I was just wondering if it would show me anything around what's happening in the regular tab.

I'm on version 50.0.2 using Linux.

I just tried version 47 and 50 on a windows machine, and it worked fine.

**Comment by glogiotatidis** [comment]
Ok so last year we worked on increasing the timeout before re-loading the webpage after clicking on X to allow the indexeddb to commit before leaving the page. Do you think that's related? (it's a different error though)

https://github.com/mozmar/snippets-service/blob/master/snippets/base/templates/base/includes/snippet.js#L522

**Comment by glogiotatidis** [comment]
btw i'll go afk for the next hours.

**Comment by ScottDowne** [comment]
I tried it on another Windows machine, and saw the error.

Yeah, might be related. I'll see if I can debug timing issues.

**Comment by ScottDowne** [comment]
I can confirm it def happens on load, when trying to open indexdb, and it def goes away if I clear everything by removing the `.mozilla` directory in my home folder, which, is essentially a fresh install at this point.

I don't think it's a simple matter of deleting cache, or the storage, as I think there is some sort of corruption in the data which is causing it to not properly clear, maybe?

I dunno, but I'm pretty sure it's not related to the timeout, and I'm pretty sure it's fringy.

I would be OK with closing this, and keeping an open eye for issues like this. So far, I havn't had any reports of this happening to a non employee.

**Comment by glogiotatidis** [comment]
OK let's keep an eye on this for the next days. Maybe the Fx folks know more. Thanks for all your investigation @ScottDowne  :)

**Comment by glogiotatidis** [comment]
We provided a reasonable work-around for this. This year's campaign will run on AS.
